### ISSUE TITLE
menu being hidden

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#18]
On the Home page as well other Sub pages the top menu gets hidden under the SSSVV logo.
The menu item HOME and ACTIVITIES are partially hidden. See snapshot below. This needs
to be corrected.

**Comment by hn-88** [comment]
try changing the css 
@media screen and (max-width:991px)
line 10 col 29069 in
sssvv-landing-page.webflow.0dd18fed3.css

**Comment by hn-88** [comment]
Have created another option where the logo is not so transparent. Please check this version with screen resolutions lower than 1200x800 also (by just resizing your browser window). 
https://www.srisathyasaividyavahini.org/lastq/option2.html

Here, we would find the menu being hidden / overwritten by the logo, since there is not enough place for all the verbose menu items.

**Comment by hn-88** [comment]
https://www.srisathyasaividyavahini.org/lastq/option1.html
is a sort of transparent logo.

https://www.srisathyasaividyavahini.org/lastq/option2.html
is where the menu gets hidden by the logo for smaller screens.

https://www.srisathyasaividyavahini.org/lastq/option3.html
is another option, where we rejig our menu to have fewer top level menu items.

**Comment by hn-88** [comment]
Add a little padding to option3 menu, for not overlapping in hi-res screens.

**Comment by hn-88** [comment]
Since option3 is the preferred choice, added menu links accordingly to all page.
