### ISSUE TITLE
google script issue for volunteers / content champs

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#23]
For many of us, including myself the content champs and Valuable Volunteers comes as
below. I tried clearing the cache, but there is no change.

**Comment by hn-88** [comment]
This is probably due to being signed in to multiple google accounts at the same time. Possible way to fix this, would be:

 - instead of directly adding the google script to the iframe, let the iframe load a static page saved to github pages by the google script. 
 
-  if possible eliminate the iframe, and use jquery load() calls to load the content saved by the google script.  

Will work on this, might take a week or two.

**Comment by hn-88** [comment]
> This is probably due to being signed in to multiple google accounts at the same time. Possible way to fix this, would be:

No - when I'm signed in to multiple accounts on Firefox, no problems. Maybe on Chrome? Or is it an issue with embedding? To check with Chrome.

**Comment by hn-88** [comment]
Could not reproduce on Chrome also, even with multiple profiles and multiple logins.

**Comment by hn-88** [comment]
https://stackoverflow.com/questions/53433938/how-do-i-allow-a-cors-requests-in-my-google-script
for CORS, or push to github like VV/VV.html every hour or so?

**Comment by hn-88** [comment]
06de814 should have fixed the google scripts issue. Implemented hourly pushes from GAS to github.
